### ISSUE TITLE
Can not use it?

### ISSUE THREAD

**Issue by ghost** [phanxuanphucnd/Data-Augumentation#1]
Hi, there is an issue when I try your example.

AttributeError: module 'augly' has no attribute 'text'

Thanks.

**Comment by phanxuanphucnd** [comment]
Hi @ngthanhtin , i ran the tutorial and not found problem. Can you say more detailed about this issue?

can you setup the library:

>> python setup.py bdist_wheel

>> pip install dist/arizona-0.0.1-py3-none-any.whl


and run the tutorial


May be the version of augle mismatch. Can you use version augle~=0.1.6  (founed augle==0.1.10) as in the requirements? 

Thanks
